apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kmts.kafka.monitoring
spec:
  group: kafka.monitoring
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                configName:
                  type: string
                configKey:
                  type: string
            status:
              type: string
      subresources:
        status: { }
  scope: Namespaced
  names:
    plural: kmts
    singular: kmt
    kind: KMT
    shortNames:
      - kmt
