apiVersion: v1
kind: ServiceAccount
metadata:
  name: sumo-kafka-discovery-operator
  namespace: sumo-kafka-discovery-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sumo-kafka-discovery-operator
  namespace: sumo-kafka-discovery-operator
spec:
  selector:
    matchLabels:
      app: sumo-kafka-discovery-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: sumo-kafka-discovery-operator
    spec:
      serviceAccountName: sumo-kafka-discovery-operator
      containers:
      - name: operator
        image: sumo-kafka-discovery-operator:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: zkConnect
            value: 172.17.0.21:2181
          - name: kafkaClusters
            value: kafka-ingest-enriched
          - name: kafkaBasePath
            value: /service
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sumo-kafka-discovery-operator-admin
subjects:
- kind: ServiceAccount
  name: sumo-kafka-discovery-operator
  namespace: sumo-kafka-discovery-operator
roleRef:
  kind: ClusterRole
  name: sumo-kafka-discovery-operator
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sumo-kafka-discovery-operator
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - services
  - configmaps
  - pods
  verbs:
  - '*'
- apiGroups:
  - "*"
  resources:
  - deployments
  - services
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - "kafka.monitoring"
  resources:
  - kmts
  - kmts/status
  verbs:
  - '*'
